language: python
dist: xenial
python:
  - "3.7"
install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls
script:
  - python3 manage.py test mithras
  - coverage run --source=mithras manage.py test mithras
after_success: coveralls
