language: python
python:
  - "2.7"
before_install:
  - openssl aes-256-cbc -K $encrypted_70c6c5985c14_key -iv $encrypted_70c6c5985c14_iv -in mithras_rsa.enc -out mithras_rsa -d
install:
  - ./bootstrap.py
script:
  - make
after_success:
  - chmod 600 mithras_rsa
  - ssh-add mithras_rsa
  - make travis_deploy
