# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abraxas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='slug',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.CharField(db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(db_index=True, max_length=8),
        ),
    ]
