# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abraxas', '0002_auto_20160820_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_email',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_url',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
