# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abraxas', '0003_auto_20161111_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='rhash',
            field=models.CharField(default=b'', max_length=256),
        ),
    ]
