# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abraxas', '0004_image_rhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
