# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 08:05
from __future__ import unicode_literals

from django.db import migrations
import textile


def convert_to_markdown(apps, schema_editor):
    Post = apps.get_model('abraxas', 'Post')
    for post in Post.objects.filter(format='textile'):
        post.body = textile.textile(post.body).strip()
        post.format = 'markdown'
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('abraxas', '0005_auto_20161113_0747'),
    ]

    operations = [
        migrations.RunPython(convert_to_markdown)
    ]
