# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abraxas', '0007_auto_20171013_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='format',
        ),
        migrations.RemoveField(
            model_name='image',
            name='format',
        ),
        migrations.RemoveField(
            model_name='post',
            name='format',
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Moderation'), ('approved', 'Approved')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='rhash',
            field=models.CharField(default='', max_length=256),
        ),
    ]
